### ISSUE TITLE
tracing分支 在生成最后的切片不会停止

### ISSUE THREAD

**Issue by bersarker** [OpenXiangShan/NEMU#101]
Tracing分支的NEMU切完最后一片后，会停着不动，没有正常退出，如下图所示。生成完最后一片后，会接着生成一片为0000.gz，然后就停着不动了，不能正常退出，请问是什么问题呢？
![image](https://user-images.githubusercontent.com/52983365/183233002-8dec8d76-e0ba-4445-9335-a92bd24fbf68.png)

**Comment by shinezyy** [comment]
SPEC跑完之后有没有执行 after workload？（一个elf，里面调用了NEMU的伪指令来退出执行）

**Comment by RichardRo** [comment]
用tracing分支也遇到这个问题，同样是生成所有checkpoint之后还会继续生成一个_0_0.000000_.gz，然后卡住。
用了after workload。
cpb-bk分支没这个问题。

大概比了一下tracing和cpt-bk代码，感觉是不是tracing分支退出checkpoint的判断有点问题？
cbt-bk分支在serializer.notify_taken(icount); 里判断simpoint2Weights都处理完为空了，就直接exit(0); 退出了程序，见下面的比对：
![image](https://user-images.githubusercontent.com/11405192/230272396-cb36b293-dede-4e8c-b3c0-b408a8052597.png)

而tracing分支在notify_taken没有退出，退出的判断留给了 if (serializer.shouldTakeCpt(icount))，shouldTakeCpt里即使 simpoint2Weights.empty()为真，还需要 && !checkpoint_taking，这时候checkpoint_taking应该为true吧，所以最终结果是false，无法退出，继续进行checkpoint？
![image](https://user-images.githubusercontent.com/11405192/230272864-bd94594b-8819-4d22-9c83-f3ad062065a2.png)

**Comment by shinezyy** [comment]
This issue should be finished in #121
