### ISSUE TITLE
master上config/riscv64-xs_defconfig中需要使能CONFIG_SHARE

### ISSUE THREAD

**Issue by huangjiasen100** [OpenXiangShan/NEMU#112]
默认是不使能CONFIG_SHARE的，在make riscv64-xs_defconfig之后，会报错
/usr/bin/ld: /tmp/riscv64-nemu-interpreter.h5RMVg.ltrans0.ltrans.o: relocation R_X86_64_32S against `.bss' can not be used when making a shared object; recompile with -fPIC

**Comment by poemonsense** [comment]
这个config是不打开CONFIG_SHARE的。CONFIG_SHARE是给difftest用的

**Comment by Jeacy** [comment]
> 默认是不使能CONFIG_SHARE的，在make riscv64-xs_defconfig之后，会报错 /usr/bin/ld: /tmp/riscv64-nemu-interpreter.h5RMVg.ltrans0.ltrans.o: relocation R_X86_64_32S against `.bss' can not be used when making a shared object; recompile with -fPIC

请问你这个问题解决了吗？我也遇到这个问题了
