### ISSUE TITLE
protoc/protobuf版本不匹配

### ISSUE THREAD

**Issue by yourgods1234567** [OpenXiangShan/NEMU#113]
你好，近期编译NEMU simpoint分支时总是报如下错误:
g++ -O2 -MMD -Wall -Werror --std=c++17 -I/home/user/xs/xs-env/NEMU/src/isa/riscv64/include -I/home/user/xs/xs-env/NEMU/src/engine/interpreter -Iresource/softfloat/repo/source/include -Iresource/softfloat/repo/source/RISCV -Iresource/lz4/lib -Iresource/zstd/lib -Iresource/CRoaring/include -I/home/user/xs/xs-env/NEMU/include -I/home/user/xs/xs-env/NEMU/lib-include -I/home/user/xs/xs-env/NEMU/resource -O2 -MMD -Wall -Werror -I/home/user/xs/xs-env/NEMU/src/isa/riscv64/include -I/home/user/xs/xs-env/NEMU/src/engine/interpreter -Iresource/softfloat/repo/source/include -Iresource/softfloat/repo/source/RISCV -Iresource/lz4/lib -Iresource/zstd/lib -Iresource/CRoaring/include -I/home/user/xs/xs-env/NEMU/include -I/home/user/xs/xs-env/NEMU/lib-include -D__ISA__=riscv64 -I/usr/local/include -O2 -flto   -D__ISA_riscv64__=1 -c -o /home/user/xs/xs-env/NEMU/build/obj-riscv64-nemu-interpreter/src/inst_trace/protoio.opp src/inst_trace/protoio.cpp
In file included from src/inst_trace/inst_dep_record.pb.cpp:4:
/home/user/xs/xs-env/NEMU/include/inst_trace/inst_dep_record.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^~~~~
/home/user/xs/xs-env/NEMU/include/inst_trace/inst_dep_record.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^~~~~
/home/user/xs/xs-env/NEMU/include/inst_trace/inst_dep_record.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
  ^~~~~
In file included from src/inst_trace/packet.pb.cpp:4:
/home/user/xs/xs-env/NEMU/include/inst_trace/packet.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is

看错误是protoc自动生成的头文件在做版本校验时报错，既然是protoc自动生成的文件是否将原.proto文件公布出来，然后在编译过程中自动生成更合适些？谢谢

**Comment by KeithPiTsui** [comment]
1. 请问这个有解决吗？
2. 原.proto文件有公布出来吗？
