### ISSUE TITLE
master 分支编译的 NEMU 链接出错

### ISSUE THREAD

**Issue by BL-GS** [OpenXiangShan/NEMU#140]
按照[指导书](https://xiangshan-doc.readthedocs.io/zh_CN/latest/tools/xsenv/###%E7%94%9F%E6%88%90%E9%A6%99%E5%B1%B1%E6%A0%B8%E7%9A%84%E4%BB%BF%E7%9C%9F%E7%A8%8B%E5%BA%8F)走流程，执行 `make riscv64-xs-ref_deconfig && make -j` 时出错，如下图：
![image](https://github.com/OpenXiangShan/NEMU/assets/78342819/9e429cd8-0e37-4c2a-8020-7dc6c806049f)
![image](https://github.com/OpenXiangShan/NEMU/assets/78342819/f06d1641-c312-4835-808d-965af17ece4e)
在 softfloat 中编译选项（NEMU/resource/softfloat/repo/build/Linux-x86_64-GCC/Makefile 46:48)中添加 `-fPIC` 后，才能够正常链接和运行：
```Makefile
COMPILE_C = \
  gcc -c -fPIC -Werror-implicit-function-declaration -DSOFTFLOAT_FAST_INT64 \
    $(SOFTFLOAT_OPTS) $(C_INCLUDES) -O2 -o $@
```

此外，执行  `make riscv64-xs_deconfig && make -j` 是能够正常编译链接执行的

**Comment by poemonsense** [comment]
可以尝试`make clean-all`之后重新走已有的步骤
