### ISSUE TITLE
profiling运行ready-to-run目录下的coremark负载，制作不出bbv文件

### ISSUE THREAD

**Issue by DimanChauncey** [OpenXiangShan/NEMU#253]
我的命令是： 
$NEMU_HOME/build/riscv64-nemu-interpreter coremark-2-iteration.bin -D /home/zxk/nemu_result -w coremark10000 -C profiling -b --simpoint-profile --cpt-interval 10000 -r $NEMU_HOME/resource/gcpt_restore/build/gcpt.bin

详细输出如下：
[src/monitor/monitor.c:154,parse_args] Doing Simpoint Profiling
[src/checkpoint/path_manager.cpp:40,init] Cpt id: -1
[src/checkpoint/path_manager.cpp:62,setOutputDir] Created /home/zxk/nemu_result/profiling/coremark10000/

[src/checkpoint/simpoint.cpp:81,init] Doing simpoint profiling with interval 10000
[src/memory/paddr.c:81,init_mem] mmap memory to anonymous file
[src/device/io/mmio.c:18,add_mmio_map] Add mmio map 'clint' at [0x0000000038000000, 0x000000003800ffff]
[src/isa/riscv64/init.c:70,init_isa] NEMU will start from pc 0x80000000
[src/monitor/monitor.c:308,init_monitor] You are providing a gcpt restorer when doing simpoing profiling, If you didn't link the program correctly, this will corrupt your memory/program.
[src/monitor/image_loader.c:56,load_img] Loading Gcpt restorer form cmdline: /root/NEMU/resource/gcpt_restore/build/gcpt.bin

[src/monitor/image_loader.c:83,load_img] Warning: size is larger than img_size(upper limit), please check if code is missing. size:1100 img_size:f00
[src/monitor/image_loader.c:88,load_img] Fread from file because less than 512MB

[src/monitor/image_loader.c:120,load_img] Read 3840 bytes from file /root/NEMU/resource/gcpt_restore/build/gcpt.bin to 0x80000000
[src/monitor/image_loader.c:56,load_img] Loading image (bbl/bare metal app) from cmdline: coremark

[src/monitor/image_loader.c:88,load_img] Fread from file because less than 512MB

[src/monitor/image_loader.c:120,load_img] Read 18984 bytes from file coremark to 0x800a0000
[src/device/io/port-io.c:15,add_pio_map] Add port-io map 'uartlite' at [0x00000000000003f8, 0x0000000000000404]
[src/device/io/mmio.c:18,add_mmio_map] Add mmio map 'uartlite' at [0x0000000040600000, 0x000000004060000c]
[src/device/io/port-io.c:15,add_pio_map] Add port-io map 'rtc' at [0x0000000000000048, 0x000000000000004f]
[src/device/io/mmio.c:18,add_mmio_map] Add mmio map 'rtc' at [0x00000000a1000048, 0x00000000a100004f]
[src/device/io/port-io.c:15,add_pio_map] Add port-io map 'screen' at [0x0000000000000100, 0x0000000000000107]
[src/device/io/mmio.c:18,add_mmio_map] Add mmio map 'screen' at [0x0000000040001000, 0x0000000040001007]
[src/device/io/mmio.c:18,add_mmio_map] Add mmio map 'vmem' at [0x0000000050000000, 0x00000000500752ff]
[src/device/io/port-io.c:15,add_pio_map] Add port-io map 'keyboard' at [0x0000000000000060, 0x0000000000000063]
[src/device/io/mmio.c:18,add_mmio_map] Add mmio map 'keyboard' at [0x00000000a1000060, 0x00000000a1000063]
[src/device/io/mmio.c:18,add_mmio_map] Add mmio map 'sdhci' at [0x0000000040002000, 0x000000004000207f]
[src/device/sdcard.c:121,init_sdcard] Can not find sdcard image: 
[src/monitor/monitor.c:37,welcome] Debug: OFF
[src/monitor/monitor.c:42,welcome] Build time: 19:06:20, Jan  8 2024
Welcome to riscv64-NEMU!
For help, type "help"
Running CoreMark for 2 iterations
2K performance run parameters for coremark.
[0]ERROR! list crc 0xbd52 - should be 0xe714
[0]ERROR! state crc 0x6f31 - should be 0x8e3a
CoreMark Size    : 666
Total time (ms)  : 36480
Iterations       : 2
Compiler version : GCC10.2.0
seedcrc          : 0xe9f5
[0]crclist       : 0xbd52
[0]crcmatrix     : 0x1fd7
[0]crcstate      : 0x6f31
[0]crcfinal      : 0x0026
Finised in 36480 ms.
Errors detected
[src/cpu/cpu-exec.c:436,cpu_exec] nemu: HIT GOOD TRAP at pc = 0x00000000800a26ba
[src/cpu/cpu-exec.c:440,cpu_exec] trap code:0
[src/cpu/cpu-exec.c:76,monitor_statistic] host time spent = 5854 us
[src/cpu/cpu-exec.c:78,monitor_statistic] total guest instructions = 466897
[src/cpu/cpu-exec.c:79,monitor_statistic] simulation frequency = 79756918 instr/s
PPM correct: 0, PPM mispred: 0
MPKI: 0.000000
[src/profiling/betapoint_profiling.cpp:338,onExit] numLoad: 0, numStore: 0
[src/profiling/betapoint_profiling.cpp:339,onExit] Footprint: 0 cacheblocks, 0 KiB 

[src/profiling/betapoint_profiling.cpp:213,dumpStride] Dump stride histogram
[src/profiling/betapoint_profiling.cpp:251,dumpStride] global stride total: 0
[src/profiling/betapoint_profiling.cpp:251,dumpStride] global stride total: 0
[src/profiling/betapoint_profiling.cpp:288,dumpStride] local stride total: 0, local pc count: 0
[src/profiling/betapoint_profiling.cpp:288,dumpStride] local stride total: 0, local pc count: 0
[src/profiling/betapoint_profiling.cpp:351,dumpDistinctStrideInc] Dump new distinct strides : 0
[src/profiling/betapoint_profiling.cpp:363,dumpFootPrintInc] Dump footprint increments: 0
[src/profiling/betapoint_profiling.cpp:312,calcReuseMatrix] Dump Reuse matrix
[src/profiling/betapoint_profiling.cpp:502,onExit] Dump critical path size: 0
[src/profiling/betapoint_profiling.cpp:509,onExit] Dump ppm miss count: 1
[src/utils/state.c:11,is_exit_status_bad] NEMU exit with good state: 2, halt ret: 0

生成的bbv文件为空。

**Comment by shinezyy** [comment]
https://xiangshan-doc.readthedocs.io/zh-cn/latest/tools/simpoint/

1. 因为checkpoint的原理，我们不支持在 M 态下生成checkpoint([Issue #54](https://github.com/OpenXiangShan/NEMU/issues/54))， 因此 workload 需要运行在 S 态或 U 态下运行，比如 Linux 上运行 SPEC2006。
2. NEMU 默认不会进入 checkpoint 模式，需要使用 NEMU 自定义指令进行模式转换。

**Comment by shinezyy** [comment]
如果一定要在M态生成checkpoint，运行时加一个参数--dont-skip-boot。但是这样得到的checkpoint不保证能正确恢复
