### ISSUE TITLE
Debian Config：no entry for main/binary-riscv64/Packages

### ISSUE THREAD

**Issue by DLDLLDDL** [OpenXiangShan/NEMU#259]
sudo debootstrap --arch=riscv64 --keyring /usr/share/keyrings/debian-archive-keyring.gpg --include=debian-ports-archive-keyring unstable /mnt http://deb.debian.org/debian-ports
按照官方教程 当执行上述命令式，出下问题
Can't verify that target arch works
I: Checking Release signature
I: Valid Release signature (key id 01C2D6F3D1A46AD1C0DC2F3D8D69674688B6CB36)
E: Invalid Release file, no entry for main/binary-riscv64/Packages
请问是debian现在不支持riscv64吗，--arch换成x32是可以的

**Comment by poemonsense** [comment]
Have a try with this: https://github.com/OpenXiangShan/NEMU/pull/264
