### ISSUE TITLE
checkpoint版本的bbl构建出现错误,initramfs-spec.txt这个脚本中的spec06-rv64gcb-gcc12.2.0-o3/astar_base.rv64gcb-gcc12.2.0-o3这个文件找不到找不到

### ISSUE THREAD

**Issue by YudeFang** [OpenXiangShan/NEMU#269]
![image](https://github.com/OpenXiangShan/NEMU/assets/49511258/e337b5de-9aeb-41af-9b0d-827376f819c1)
使用的版本 
riscv-pk noop分支 
riscv-roots checkpoint分支
riscv-linux nanshan分支

spec2006正常编译成功

**Comment by xyyy1420** [comment]
请根据需求自行修改initramfs-spec.txt

**Comment by YudeFang** [comment]
> 请根据需求自行修改initramfs-spec.txt
![image](https://github.com/OpenXiangShan/NEMU/assets/49511258/3b4f8389-1a1f-4966-879e-f4639a2b1ef6)

config.log详细错误信息
112 compilation terminated.113 configure:2357: $? = 1114 configure:2377: checking whether the C compiler works115 configure:2399: riscv64-unknown-elf-gcc    conftest.c  >&5116 /usr/lib/riscv64-unknown-elf/bin/ld: cannot find crt0.o: No such file or directory 117 /usr/lib/riscv64-unknown-elf/bin/ld: cannot find -lc118 /usr/lib/riscv64-unknown-elf/bin/ld: cannot find -lgloss119 collect2: error: ld returned 1 exit status
![image](https://github.com/OpenXiangShan/NEMU/assets/49511258/0f4a726b-3be0-4610-8f52-4d9e3dfedd39)
