### ISSUE TITLE
计算speccpu2006 分数时每个case的总指令数

### ISSUE THREAD

**Issue by qqli579** [OpenXiangShan/NEMU#272]
> 或者这么算： 总执行时钟数 = Sigma(每个片段所代表的cluster的时钟周期数) 一个片段所代表的cluster的时钟周期数 = 这个片段所代表的cluster的指令数 / 这个片段的CPI 这个片段所代表的cluster的指令数 = 总指令数 * 权重
> 
> 这个计算方法化简之后和上面说的算加权平均CPI的算法是一样的。
这里的总指令数是NEMU采集simpoint的时候log里打印出来total guest instructions吗？
```
[src/cpu/cpu-exec.c:95,monitor_statistic] total guest instructions = 254,652,097,553
```
还有你们给的specCPU2006的分数，在采集simpoint的时候用的--cpt-interval是多少？

_Originally posted by @qqli579 in https://github.com/OpenXiangShan/NEMU/issues/95#issuecomment-1977920115_

**Comment by shinezyy** [comment]
> 这里的总指令数是NEMU采集simpoint的时候log里打印出来total guest instructions吗？

是的
