### ISSUE TITLE
当前NEMU中对异常V扩展指令的覆盖存在部分缺陷

### ISSUE THREAD

**Issue by prjmoriarty** [OpenXiangShan/NEMU#357]
1. 对于Vector Floating-Point指令，其SEW的可取值应与CPU支持的浮点扩展统一，当不支持半浮点指令时，对sew为16bit的向量浮点指令应识别为非法指令，当前NEMU中没有此类型判断
2. 对于Vector Mask-Register Logoical指令，vm=0为reserved，当vm为0时，应识别为非法指令异常，当前NEMU中没有此类型判断

**Comment by Ziyue-Zhang** [comment]
Thx. I'll fix it soon

**Comment by Ziyue-Zhang** [comment]
This problem now be solved with #359
