### ISSUE TITLE
riscv: Compilation failed when CONFIG_DEBUG and CONFIG_SVINVAL are both defined

### ISSUE THREAD

**Issue by ljwljwljwljw** [OpenXiangShan/NEMU#45]
`CONFIG_SVINVAL` is defined by default and `CONFIG_DEBUG` is not defined by default, however if I define both of them, there will be a compilation error(in standalone mode):

```
src/cpu/cpu-exec.c: In function ‘execute’:
src/cpu/cpu-exec.c:159:5: error: label ‘exec_sinval_vma’ used but not defined
  159 |     MAP(INSTR_LIST, FILL_EXEC_TABLE)
      |     ^~~
src/cpu/cpu-exec.c:159:5: error: label ‘exec_sfence_inval_ir’ used but not defined
src/cpu/cpu-exec.c:159:5: error: label ‘exec_sfence_w_inval’ used but not defined
```

I think this may be caused by: 

https://github.com/OpenXiangShan/NEMU/blob/eaa07cdc3f2adb269f5201fc0c52a770f22cf15a/src/isa/riscv64/instr/priv/decode.h#L7-L27

**Comment by Lemover** [comment]
It is fixed. see:
https://github.com/OpenXiangShan/NEMU/pull/47

Description:
when CONFIG_DEBUG, these priv function has their own THelper and EHelper. SVINVAL's EHelpers are forgot to add.
