### ISSUE TITLE
[Bug Report] `mie` register not implemented correctly

### ISSUE THREAD

**Issue by Donkey-Hao** [OpenXiangShan/NEMU#517]
According to the privileged [specification](https://riscv.org/technical/specifications/) in chapter **3.1.9. Machine Interrupt Registers**, some bits in MIE are set to zero. 

![image](https://github.com/user-attachments/assets/82ba2a05-6a2e-40fe-99af-8a45b955439e)

However, if we write `0xffffffff` to `mie`, the NEMU will set it to `0xffffffff`. 

![d6b3a49b95a1de3da74c349878549f4](https://github.com/user-attachments/assets/fefe5ae2-db34-4af9-9612-4fa46407496d)

The bug was found when I tested Xiangshan. This is the test program [mie_bug.zip](https://github.com/user-attachments/files/16960329/mie_bug.zip).

Here are some env information:

**NEMU commit:** 3033a69f,
**xs-env commit:** master,
**Xiangshan commit:** 8fae59bba.

**Comment by huxuan0307** [comment]
Thank you for your bug reporting. I'm handling this.

**Comment by Donkey-Hao** [comment]
Hi @huxuan0307,
I have tested this bug in the newest version NEMU, commit id is `821ea961`. I changed some code in order to run `./build/riscv64-nemu-interpreter -d ./ready-to-run/riscv64-spike-so -b mie.bin`.
<img width="1271" alt="image" src="https://github.com/user-attachments/assets/d202953d-c338-4e87-a2a2-eaaf4d3dea1d">

Actually, I doubt the reference spike is not correct because I ran the code in spike, the 1.1.1-dev version, the right value is `mie = 0x0000000000000aaa` after we write it. 
<img width="490" alt="image" src="https://github.com/user-attachments/assets/da0c557d-5402-4928-b0a8-b16d70fce539">

Is there a way to run NEMU like spike step by step? I have not found it. I want to help to improve NEMU.

**Comment by sinceforYy** [comment]
In `src/isa/riscv64/system/priv.c`, you can look at the source code for writing the mie register. We now support the `RV_H` and `RV_SSCOFPMF` extensions, so the corresponding bits of mie are readable and writable. 

We made a modification based on Spike, you can get it in https://github.com/OpenXiangShan/riscv-isa-sim. If you want to modify and generate spike-so that diff with NEMU, you can read `README` in `riscv-isa-sim/difftest/`

Besides, You can remove the -b option and run `./build/riscv64-nemu-interpreter -d ./ready-to-run/riscv64-spike-so mie.bin`. Execute `help` to view options.

**Comment by Donkey-Hao** [comment]
Hi @sinceforYy, thanks for your reply.
I am sorry for confused you, this problem is not about `the corresponding bits of mie are readable and writable`. No matter what extensions Xiangshan supports, some bits in `mie` must be zero, such as `mie.{0, 2, 4, 6, 8}`. 
![image](https://github.com/user-attachments/assets/b1adb57d-d92d-44bb-b3a0-f7ff1548693a)
As you can see in my initial comment: `mie = 0xffffffff`, which means  `mie.{0, 2, 4, 6, 8}` is not zero. Here is my question,  `mie.{0, 2, 4, 6, 8}` === 0, is that right? Please correct me if I am wrong. 
Sincerely.

**Comment by Donkey-Hao** [comment]
Thanks for your reply @sinceforYy.

I have RTFM in **chapter 17 & 18.4**, NEMU `821ea961` version is right, but [3033a69](https://github.com/OpenXiangShan/NEMU/commit/3033a69fb8cdd9939ebb43315f86f38ab97346fe) was wrong, as we can see the picture in my first comment:
![366359785-fefe5ae2-db34-4af9-9612-4fa46407496d](https://github.com/user-attachments/assets/1af8e382-696a-4a4e-94d6-bb838cad670d)
Yes, xiangshan supports the RV_H and RV_SSCOFPMF extensions, so NEMU `821ea961` version is right when we write 0xffffffff to `mie`:

>C17: Note that the new count overflow interrupt will be treated as a standard local interrupt that is assigned to bit 13 in the mip/mie/sip/sie registers.
![image](https://github.com/user-attachments/assets/def8d82c-78aa-4579-999f-6fbacd65e2da)

This bug had been fixed.
