### ISSUE TITLE
南湖分支NEMU编译报错src/memory/paddr.c:502:12: error: 'result' may be used uninitialized in this function [-Werror=maybe-uninitialized'

### ISSUE THREAD

**Issue by qiaomufenlin** [OpenXiangShan/NEMU#530]
按官方教程，执行报错
![image](https://github.com/user-attachments/assets/17bffdcc-1113-46c5-9d93-f5044611f860)
![image](https://github.com/user-attachments/assets/f287666b-202b-4f00-b751-d2a8e03eea18)

**Comment by Lemover** [comment]
Please provide a complete reproduction process starting from downloading from GitHub.

**Comment by qiaomufenlin** [comment]
@

**Comment by qiaomufenlin** [comment]
close
