### ISSUE TITLE
[Bug Report] mtval register incorrectly updated after illegal instruction exception triggered by executing c.lwsp with rd=x0

### ISSUE THREAD

**Issue by fly-1011** [OpenXiangShan/NEMU#584]
**Describe the bug**

When testing XiangShan using NEMU as a reference model, an `illegal instruction exception` occurs when executing instruction `c.lwsp zero, 0(sp)` (`which is illegal because rd = x0, violating the constraints in the RISC-V compressed ISA`). NEMU does not correctly set the `mtval `CSR during the illegal instruction exception.

**To Reproduce**

Run the following command to execute the test image with NEMU as the reference model:

`./build/emu -b 0 -e 0 -i id_1046.img --diff /xs-env/XiangShan/ready-to-run/riscv64-nemu-interpreter-so`

![image](https://github.com/user-attachments/assets/e0d06a84-2dc3-431e-aabe-cc691896d88f)
![image](https://github.com/user-attachments/assets/c9eb7a97-3816-47ed-bc14-842d77886d84)

**Expected behavior**

When an illegal instruction exception occurs, `NEMU` should set mtval to the encoding of the illegal instruction like `xiangshan`.

**Actual Behavior**

NEMU sets mtval to the encoding of the previous instruction `jr tp` (`0x0000000000020067`).

**Necessary information on versions**

Xiangshan:commit ea2894c8c273b00083141d9258b412ed910b28f9 (HEAD, origin/master, origin/HEAD)

Ready-to-run:commit 2ade2e3879e019f6400cb33efbb62513166d139b (HEAD, origin/master, origin/HEAD)

NEMU commit: 300b282c158dbd2d4bd23edf4f682b27a0d711be

**Additional information**

This is the test program  [id_1046.zip](https://github.com/user-attachments/files/17361703/id_1046.zip)

**Comment by lewislzh** [comment]
Thank you for your bug report！
We have fixed this bug, which was caused by NEMU not correctly passing the relevant instruction information to the exception handling part when handling illegal instruction exceptions in RVC extension. The current fix unifies the passing of instruction information after the long jump.
