### ISSUE TITLE
2022.4.6 NEMU 更新后的报错

### ISSUE THREAD

**Issue by erdevonmatteo11** [OpenXiangShan/NEMU#62]
用新版本 NEMU (master 分支) ，报了错：

![屏幕截图 2022-04-06 141000](https://user-images.githubusercontent.com/57934484/161908710-fd5d3a84-bf19-407c-a3bf-2c970f82a76e.png)

接着，我发现是有新文件 NEMU/src/checkpoint/cpt_env.c ，要在里面手动赋值。请问怎么改比较好？

**Comment by AugustusWillisWang** [comment]
新引入的代码有点问题, 可以先回滚一个版本.

**Comment by shinezyy** [comment]
可以暂时用 f357d0c2d9f82ae6b9196547089838da14d74326
