### ISSUE TITLE
When an illegal instruction exception occurs, the value of the mstatus register is set incorrectly

### ISSUE THREAD

**Issue by fly-1011** [OpenXiangShan/NEMU#626]
**Describe the bug**

When testing XiangShan using NEMU as a reference model, an illegal instruction exception occurs when executing instruction `csrrs t3, hpmcounter3, t1`. During the illegal instruction exception, the mstatus register differs between NEMU and Xiangshan, specifically the WPRI bit (bit 42) is incorrectly modified.

**To Reproduce**

The assembly test program is as follows:
```
_start:

    li     t0, 0x8000000a00107a00     
    csrw    mstatus, t0 
    li t2,0x0
    li t3,0x0
    li t1,0x0      
    csrr  t2, mstatus
    csrrs   t3, hpmcounter3, t1   
    csrr  t2, mstatus 
    nop       
    .word 0x4002  # c.lwsp zero, 0(sp)
```
Run the following command to execute the test image with NEMU as the reference model:
`./build/emu -b 0 -e 0 -i  mstatus.img  --diff /xs-env/XiangShan/ready-to-run/riscv64-nemu-interpreter-so `
![image](https://github.com/user-attachments/assets/4ce6bfce-b166-4429-9c91-f0c0e15de853)
![image](https://github.com/user-attachments/assets/d332b86e-43cf-49ab-ad6f-49c34923ba8c)

**Actual Behavior**

Bit 42 of the mstatus register in NEMU is set to 1.

![image](https://github.com/user-attachments/assets/f733fb9f-6840-4c2b-9b09-0c5aadd82dee)

**Necessary information on versions**
xiangshan:commit cb62726bba95608b79405d17edb74f5ea430c4f2 (HEAD -> master, origin/master, origin/HEAD)
ready-to-run:commit 52673fa06b253658804d345d25074353ec615751

**Additional information**
This is the test program [mstatus.zip](https://github.com/user-attachments/files/17598141/mstatus.zip)

**Comment by lewislzh** [comment]
The MDT bit is introduced by the Smdbltrp extension. Currently, dbltrp has been merged into both the NEMU and master , and testing XiangShan and ready-to-run with the latest master showed no issues. However, since mtvec was not set during the test, a critical error is reported.
