### ISSUE TITLE
mcause mismatch in NEMU due to checking misalignment before confirming MMIO address in store instruction

### ISSUE THREAD

**Issue by fly-1011** [OpenXiangShan/NEMU#629]
**Describe the bug**

While using NEMU as a reference model to test XiangShan, I observed that for the `fld` instruction, when an address misaligned and Load Access Fault occur, XiangShan reports an `mcause` of `5`, whereas NEMU reports an `mcause `of `4`. Under similar conditions with the `sw` instruction, XiangShan reports an `mcause` of `7`, while NEMU reports an `mcause` of `6`.

The `fld` instruction discrepancy was previously reported and addressed in https://github.com/OpenXiangShan/XiangShan/issues/3829. However, upon reviewing the fix, it appears that the changes only apply to `load instructions`, and `store instructions` have not yet been modified.

**To Reproduce**
![image](https://github.com/user-attachments/assets/18e564b8-013c-448f-a5de-bdab7639e3fd)
![image](https://github.com/user-attachments/assets/6d4d43e1-368a-49e1-bfcc-2222be4cde7c)

**Necessary information on versions**
xiangshan:commit 7af39ad2ddb1305b2c4ddf4c3a9663a7c3615fa6 
ready-to-run:commit c09f524c6ecb43cd047b226e2da4aad7edd05702

**Comment by NewPaulWalker** [comment]
Thank you for your issue and you are right. I have made the necessary modifications in the corresponding PR.
