### ISSUE TITLE
Some illegal instruction handling errors

### ISSUE THREAD

**Issue by youzi27** [OpenXiangShan/NEMU#637]
**Describe the bug**

The NEMU encounters certain illegal instructions (e.g., 0x70f98b6b) but fails to raise an illegal instruction exception properly.

**Error log or Screenshots**

![image](https://github.com/user-attachments/assets/927ec296-8fec-4a62-93bd-1bf886f8c867)

**Necessary information on versions**
ready-to-run's NEMU commit: c9c1451

**Comment by NewPaulWalker** [comment]
Thank you for your issue.
We intended to treat instructions ending with `0x6b` as instructions for simulation termination.
However, there is currently an inconsistency between XiangShan and NEMU in the definition of such instructions.
XiangShan defines it as:
```scala
def TRAP = BitPat("b000000000000?????000000001101011")
```
while NEMU defines it as:
```c
def_INSTR_TAB  ("??????? ????? ????? 000 ????? 11010 ??",         nemu_trap);
```

As a result, XiangShan considers your instruction `0x70f98b6b` as not a valid simulation-ending instruction and throws an illegal instruction exception, while NEMU considers it as an instruction to end the simulation.
This causes the inconsistency between the two.
And I have now updated NEMU to make it consistent with XiangShan.
