### ISSUE TITLE
Incorrect GVA setting in mstatus

### ISSUE THREAD

**Issue by youzi27** [OpenXiangShan/NEMU#640]
**Describe the bug**

In M-mode, mstatus's GVA value is incorrectly set when a trap is thrown during ebreak.

**To Reproduce**
```
.section .text
.globl _start
_start:

    nop
    li x26, 0x800000ca007e7a8a
    csrw mstatus, x26
    ebreak      
    
    nop

```
**Expected behavior**

> Field GVA (Guest Virtual Address) is written by the implementation whenever a trap is taken into M-mode. For any trap (breakpoint, address misaligned, access fault, page fault, or guest-page fault) that writes a guest virtual address to mtval, GVA is set to 1. For any other trap into M-mode, GVA is set to 0.

**Error log or Screenshots**

![image](https://github.com/user-attachments/assets/ac6f4442-1c99-4ebb-aef8-315ff6b9d96c)

**Necessary information on versions**
ready-to-run's NEMU commit: c9c1451

**Comment by NewPaulWalker** [comment]
Thank you for your issue.
You wrote 1 to mprv, 1 to mpv, and 3 to mpp in mstatus, but after executing the ebreak instruction, the gva in mstatus is still 1 in NEMU.
This is indeed a bug in NEMU, and I have fixed the set/clear logic for gva, which should have fixed the issue.
