### ISSUE TITLE
There is a difference in the mcause value when executing flh and fsh instructions

### ISSUE THREAD

**Issue by fly-1011** [OpenXiangShan/NEMU#644]
**Describe the bug**

Note: The previous issue has been fixed. For details, see: https://github.com/OpenXiangShan/NEMU/pull/628

When I use nemu as the reference model to test Xiangshan, there is a difference in the `mcause `value when executing `fsh ft0, 9(sp) `or` flh ft0, 9(sp) `instructions.

The assembly code is as follows:
```
.section .text
.globl _start
_start:
    li     t0, 0x8000000a00104a00     
    csrw    mstatus, t0 
    fsh     ft0, 9(sp)   #flh     ft0, 9(sp) 
```

**Error log or Screenshots**

1. Execute `fsh ft0, 9(sp)` command with `--diff /xs-env/NEMU/build/riscv64-nemu-interpreter-so` parameter

![image](https://github.com/user-attachments/assets/0fb7c82d-0a26-48e6-829b-8f1c4bf4ec51)
![image](https://github.com/user-attachments/assets/cd2dc706-0458-4a0e-b463-59bea9aaaa72)

2. Execute `flh ft0, 9(sp)` command with `--diff /xs-env/NEMU/build/riscv64-nemu-interpreter-so` parameter

![image](https://github.com/user-attachments/assets/fe7a3bf0-cd30-4433-85c7-f99a5b092316)
![image](https://github.com/user-attachments/assets/32fc45be-0421-4120-b919-54fedfdb2140)

**Necessary information on versions**
- NEMU 34ba2259558ed89f5a042179ef0a9131e53ce037 (HEAD, origin/master, origin/HEAD)
- xiangshan:commit 7af39ad2ddb1305b2c4ddf4c3a9663a7c3615fa6 (HEAD -> master, origin/master, origin/HEAD)

**Comment by NewPaulWalker** [comment]
This is a bug in XiangShan, as described in the [issue](https://github.com/OpenXiangShan/XiangShan/issues/3839).

**Comment by NewPaulWalker** [comment]
> Thank you for your prompt reply. From your description, this seems to be another bug in xiangshan. Do I need to submit a new issue in the xiangshan repository to explain this?

I think it's a good idea, because these are two different bugs.
