### ISSUE TITLE
mnscratch register related issues

### ISSUE THREAD

**Issue by fly-1011** [OpenXiangShan/NEMU#661]
**Describe the bug**

When using nemu as a reference model to test Xiangshan, it was found that when executing `mnscratch` related instructions `csrrs t0, mnscratch, a1`, Xiangshan and nemu behaved inconsistently.

**Error log or Screenshots**

![image](https://github.com/user-attachments/assets/17afde7e-cce7-4b88-a100-d99b6c99a06f)

![image](https://github.com/user-attachments/assets/6e7eda78-a713-4f71-bc0e-18b22e5fb74c)

**Necessary information on versions**
- NEMU version: 39f546c42275cb9bc2f74170e7ff6486c98ef4c9
XiangShan commit dd02bc3f0e1adcf5fbaee614420772a94ccc0226 (HEAD -> master, origin/master, origin/HEAD)
ready-to-run:a449a38534ec8330842ad5e975b872686b421ebc

**Comment by lewislzh** [comment]
@fly-1011 
Similar issues can be found in detail at: https://github.com/OpenXiangShan/XiangShan/issues/3882#issuecomment-2481809416
