### ISSUE TITLE
When access to `hcontext` NEMU does not trap `EX_II`

### ISSUE THREAD

**Issue by ha0lyu** [OpenXiangShan/NEMU#662]
According to chapter 4.2 priv:

> The CONTEXT bit in mstateen0 controls access to the scontext and hcontext CSRs provided by the Sdtrig extension. The CONTEXT bit in hstateen0 controls access to the scontext CSR provided by the Sdtrig extension.

we read `mstateen0` is `0xdc00000000000001`, and CONTEXT bit is zero, which means we can not access `hcontext & scontext`.
<img width="1122" alt="image" src="https://github.com/user-attachments/assets/09f1a134-771b-4540-a358-3758575e82eb">

However, when we read this register, XiangShan trap EX_II, NEMU does not.

<img width="802" alt="image" src="https://github.com/user-attachments/assets/26b02b04-23bb-4f61-8e6d-2adc4ebd65f3">

<img width="739" alt="image" src="https://github.com/user-attachments/assets/20175683-2f9d-4950-b8cc-83ae60e1f9ff">

[test.log](https://github.com/user-attachments/files/17791460/test.log)

**Test Case**:
```
csrr s0, mstateen0
    .word 0x6a802e73   # csrr t3, hcontext
```

**Version**:
NEMU: b9507fbc
XiangShan: 011f1effd

**Comment by NewPaulWalker** [comment]
Thank you for your issue. This is indeed a bug in NEMU.
Since the `xcontext` CSR is not implemented in XiangShan, accessing `hcontext` raises an illegal instruction exception.
However, `hcontext` and `scontext` is exist in NEMU and I will modify NEMU to make it consistent with XiangShan.
