### ISSUE TITLE
Initial Value Mismatch of Custom Register 0x5c2 Between NEMU and XiangShan

### ISSUE THREAD

**Issue by youzi27** [OpenXiangShan/NEMU#676]
**Description**

Hi there,

I noticed that the initial value of the custom CSR `0x5c2` differs between NEMU and XiangShan. I am not sure about the potential impact of this mismatch. I decided to report this because I have observed that in many cases where the behavior seems allowed by the specification, NEMU aligns with XiangShan. Therefore, I believe this might be worth investigating.

**Error log or Screenshots**
![image](https://github.com/user-attachments/assets/dc0fa93d-df69-46f9-9047-1dfbde9098e0)

**Necessary information on versions**
- ready-to-run(NEMU) commit: 8275605
- XiangShan commit: aecf601

**Comment by NewPaulWalker** [comment]
Thank you for your issue. This issue appears to be the same as https://github.com/OpenXiangShan/XiangShan/issues/3881. You can try updating NEMU https://github.com/OpenXiangShan/NEMU/commit/0b85cdcf5d7df9560fdba7f9bf5a74dc3896716b and compiling the SO yourself for testing, or you can use the updated SO I provided in https://github.com/OpenXiangShan/ready-to-run/commit/3575e659bf3a1ed0e0de74bcef848b9be666725b. Alternatively, you can wait for this https://github.com/OpenXiangShan/XiangShan/pull/3918 to be merged and then pull the updated ready-to-run submodule content for testing.
