### ISSUE TITLE
NEMU replay checkpoint have kernel panic

### ISSUE THREAD

**Issue by wuchangsheng** [OpenXiangShan/NEMU#684]
workload is opensbi and Image not bbl. checkpoint  is a kernel 6.12(GCV) and speccpu2017(GC) benchmark. 
When executing the write system call, the kernel performs vector copy and the following error occurs
![image](https://github.com/user-attachments/assets/16ebeb88-ace5-42d6-91e4-3d688a54a5e1)
The corresponding kernel code for the error is，datap is NULL
![image](https://github.com/user-attachments/assets/5f6153c1-54e4-424f-aef8-0e0636e01543)

but, profiling and checkpoint is OK
gcpt_new_mem_layout and maser branch is same

**Comment by NewPaulWalker** [comment]
Please provide more detailed information, such as your workload file, run screenshots, full logs, and the NEMU commit ID you are using.

If possible, you can try running your workload with Spike for differential testing.
