### ISSUE TITLE
 `ENVCFG` in `mstateen0` Does Not Control Access

### ISSUE THREAD

**Issue by youzi27** [OpenXiangShan/NEMU#690]
**Describe the bug**

A bug has been identified in NEMU where, in mode=1, the `ENVCFG` bit in `mstateen0` does not correctly control access to the `henvcfg` and `senvcfg` registers. These registers can still be accessed erroneously, even though such access should be restricted.

**To Reproduce**

1. Clear the `ENVCFG` bit in `mstateen0`.
2. Set to mode=1.
3. Attempt to access `xenvcfg`.

**Expected behavior**
When ENVCFG is cleared, accessing xenvcfg should trigger an illegal instruction exception.

According to the RISC-V specification: 

> The ENVCFG bit in mstateen0 controls access to the henvcfg, henvcfgh, and the senvcfg CSRs.

**Error log or Screenshots**
When access senvcfg:
![image](https://github.com/user-attachments/assets/b9c05bb6-9d9a-421a-a1a6-018fb3e8d43c)

When access henvcfg:
![image](https://github.com/user-attachments/assets/232e5a86-0a68-48e6-b4a9-59dd488d01b7)

**Necessary information on versions**
- ready-to-run's NEMU commit id: [OpenXiangShan/ready-ro-run@3575e65](https://github.com/OpenXiangShan/ready-to-run/commit/3575e65) (Date: Fri Nov 22 17:06:53 2024 +0800) 
- XiangShan commit id: https://github.com/OpenXiangShan/XiangShan/commit/aecf601e803bfd2371667a3fb60bfcd83c333027 (Date: Tue Nov 19 16:16:35 2024 +0800)

**Additional context**
None

**Comment by NewPaulWalker** [comment]
The same issue as https://github.com/OpenXiangShan/NEMU/issues/691
we can continue the discussion in that  issue.
