### ISSUE TITLE
The value of the mtval register differs when executing a specific sequence.

### ISSUE THREAD

**Issue by fly-1011** [OpenXiangShan/NEMU#696]
**Describe the bug**

When I use nemu as a reference model to test Xiangshan, there are differences in the value of the` mtval` register when executing a specific program.

**Error log or Screenshots**

![image](https://github.com/user-attachments/assets/d5ce0dcd-978d-4e9b-a2c1-770745bf174b)

![image](https://github.com/user-attachments/assets/e53f85ca-b8ac-4e68-95f8-1de3374a74ad)

This is the test program and log information：[mtval_test.zip](https://github.com/user-attachments/files/17972433/mtval_test.zip)

**Necessary information on versions**

ready-to-run:c1dc496545b9d62bb10264cd4485cb6fe7c60798
xiangshan: fcefab3267fdc4c23472db8e6bca6d6054242e8a
- NEMU version: 0b75a4555a4cac16247a5fe3659f52ea900729e8

**Comment by NewPaulWalker** [comment]
Thanks for your issue! This doesn't seem to be a bug in NEMU or XiangShan; rather, it appears that your test program is self-modifying.

The differential test indicates a mismatch in the `mtval` value for an illegal instruction: XiangShan reports `0x00000000`, while NEMU reports `0xffffffff`. Based on the disassembled file you provided, the instruction at PC `0x80003816` is encoded as `0xf0d10113`, which differs from both values mentioned above.
![1733116525486](https://github.com/user-attachments/assets/4343c115-d577-4832-b144-651e28be2ec4)


Additionally, I noticed that your program writes multiple values at address `0x80003812`, with the last two values coinciding with those reported by XiangShan and NEMU.
![1733116625048](https://github.com/user-attachments/assets/dae5eadf-4ba6-4ff6-b509-0c2fa3b8f818)
![1733116655603(1)](https://github.com/user-attachments/assets/6581959c-ea33-4731-b4dd-8e9fce6e9f2c)


Therefore, I recommend that if your program involves self-modifying code, you should use the `fence` instruction to ensure correct instruction fetching.
