### ISSUE TITLE
生成checkpoint后，如何让香山verilator emu调用它

### ISSUE THREAD

**Issue by erdevonmatteo11** [OpenXiangShan/NEMU#70]
你们好，我阅读完了你们有关checkpoint的资料，发现没有说到：如何让香山的emu调用已生成的checkpoint。请问这是如何操作呢？谢谢。

**Comment by YangQi1234** [comment]
老哥，请教一下你是怎么生成的checkpoint的？他们不是说损坏了吗，我现在用这个分支也搞不出来。
