### ISSUE TITLE
NEMU支持断点

### ISSUE THREAD

**Issue by runninglinuxkernel** [OpenXiangShan/NEMU#80]
在NEMU中设置断点，发现 NEMU可以识别到断点，但是没有停在断点上。

例如我在程序里，设置断点“w $pc == 0x80200008”

nemu) w $pc == 0x80200008
Set watchpoint #0
(nemu) c

Hint watchpoint 0 at address 0x0000000080200004, expr = $pc == 0x80200008
old value = 0x0000000000000000
new value = 0x0000000000000001

Hint watchpoint 0 at address 0x0000000080200008, expr = $pc == 0x80200008
old value = 0x0000000000000001
new value = 0x0000000000000000
Welcome RISC-V!

**Comment by wakafa1** [comment]
看起来 #84 解决了问题？

**Comment by runninglinuxkernel** [comment]
是的
