### ISSUE TITLE
合并本仓库到NJU上游？

### ISSUE THREAD

**Issue by alexfanqi** [OpenXiangShan/NEMU#86]
想请问下有没有计划将xiangshan的nemu和nju的nemu (https://github.com/NJU-ProjectN/nemu) 合并？看到上游也有些不同的功能比如itrace

我们在gentoo上给两个nemu都打了包，不过如果两个nemu能合并的话就能让包维护者和用户方便不少。

**Comment by alexfanqi** [comment]
谢谢指出。没事，因为是源码安装，所以相当于省去手动编译了。

**Comment by sashimi-yzh** [comment]
我的意思是, NJU的NEMU基本上是一个空的项目, 它是让学生通过开发来学习的, 并不是面向用户的, 所以是不是没有必要打包NJU的版本呢?

**Comment by alexfanqi** [comment]
那确实没啥必要，不过反正已经写好打包脚本了
