### ISSUE TITLE
Nemu CPU模拟器统计运行程序总指令的问题。

### ISSUE THREAD

**Issue by lico614257** [OpenXiangShan/NEMU#96]
![image](https://user-images.githubusercontent.com/80834682/180148694-ac0a7023-2101-4833-8a45-9ac1dd7ca4e9.png)
作者你好，在我使用nemu CPU 模拟器运行自己的程序时，程序运行完成会统计整个程序的指令数。但当我保持环境不变，重复运行相同的程序时，我发现这个“total guest instructions”的数值是会发生变化的，变化的幅度在0.0000025%左右，虽然变化的幅度很小很小，但是想请教一下为什么会发生小幅度的变化，这中间的原因是什么？

**Comment by shinezyy** [comment]
这有可能是因为时钟中断发生的次数不同导致的，不过也不排除其他原因，可以尝试关闭时钟中断运行（如果可行的话）
