### ISSUE TITLE
NEMU Tracing 分支 相对 cpt-bk 分支 profiling的算法差异 及 tracing的意涵是什么

### ISSUE THREAD

**Issue by KeithPiTsui** [OpenXiangShan/NEMU#98]
如题，请问NEMU的Tracing 分支profiling的算法差异，以及 tracing 的意味是什么，我可以查看哪些文献来了解。

**Comment by shinezyy** [comment]
Tracing分支里的profiling相关内容是我个人的研究项目，暂时没有文献。

**Comment by KeithPiTsui** [comment]
很好，能粗浅地分享下原理吗？
